import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {io} from 'socket.io-client';
import './styles.css';
const socket=io(import.meta.env.VITE_SERVER_URL || 'http://localhost:3001');

type Player={id:string;name:string;hand:number[];handCount:number;ready:boolean;starVote:boolean};
type Room={code:string;hostId:string;players:Player[];level:number;maxLevel:number;lives:number;stars:number;pile:number[];status:string;message:string};
function Tutorial({close}:{close:()=>void}){return <div className="modal"><div className="sheet"><button className="x" onClick={close}>×</button><h2>Como jogar</h2><p>Vocês são uma única equipe. O objetivo é jogar todas as cartas numéricas em ordem crescente, sem turnos e sem combinar sinais ou revelar números.</p><ol><li>No nível 1, cada jogador recebe 1 carta; no nível 2, recebe 2, e assim por diante.</li><li>Quando todos estiverem prontos, a rodada começa. Quem sentir que possui a menor carta disponível pode jogá-la.</li><li>Você sempre deve jogar a menor carta da sua própria mão primeiro.</li><li>Se alguém jogar uma carta enquanto existe um número menor em alguma mão, a equipe perde uma vida e todas as cartas menores são descartadas.</li><li>Uma estrela pode ser proposta. Se todos concordarem, cada jogador descarta a menor carta da própria mão e a equipe gasta 1 estrela.</li><li>Ao esvaziar todas as mãos, vocês avançam de nível. Alguns níveis concedem vida ou estrela, respeitando os limites máximos.</li><li>Vence quem completar todos os níveis. A equipe perde ao ficar sem vidas.</li></ol><p className="note">2 jogadores: 12 níveis e 2 vidas. 3 jogadores: 10 níveis e 3 vidas. 4 jogadores: 8 níveis e 4 vidas. Todos começam com 1 estrela.</p><button onClick={close}>Entendi</button></div></div>}
function App(){
 const [name,setName]=useState(localStorage.getItem('name')||''); const [joinCode,setJoinCode]=useState(''); const [room,setRoom]=useState<Room|null>(null); const [tutorial,setTutorial]=useState(true); const [err,setErr]=useState('');
 useEffect(()=>{socket.on('room',(r:Room)=>setRoom(r)); socket.on('errorMessage',(m:string)=>setErr(m)); return()=>{socket.off('room');socket.off('errorMessage');}},[]);
 const me=useMemo(()=>room?.players.find(p=>p.id===socket.id),[room]);
 const save=()=>localStorage.setItem('name',name);
 if(!room) return <main className="landing"><div className="orb"></div><section className="hero"><div className="eyebrow">JOGO COOPERATIVO DE SINCRONIA</div><h1>Mind<span>Sync</span></h1><p>Entre no mesmo ritmo. Sem turnos. Sem números falados. Apenas timing.</p><input placeholder="Seu nome" maxLength={18} value={name} onChange={e=>setName(e.target.value)} onBlur={save}/><button className="primary" disabled={!name.trim()} onClick={()=>{save();socket.emit('createRoom',{name})}}>Criar sala</button><div className="join"><input placeholder="CÓDIGO" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())}/><button disabled={!name.trim()||joinCode.length<4} onClick={()=>{save();socket.emit('joinRoom',{code:joinCode,name})}}>Entrar</button></div>{err&&<div className="error">{err}</div>}<button className="link" onClick={()=>setTutorial(true)}>Como jogar</button></section>{tutorial&&<Tutorial close={()=>setTutorial(false)}/>}</main>;
 return <main className="game"><header><div><small>SALA</small><strong>{room.code}</strong></div><div className="stats"><span>♥ {room.lives}</span><span>✦ {room.stars}</span><span>NÍVEL {room.level}/{room.maxLevel}</span></div><button className="ghost" onClick={()=>setTutorial(true)}>?</button></header>
 <section className="players">{room.players.map(p=><div className={'player '+(p.id===socket.id?'you':'')} key={p.id}><span className="avatar">{p.name[0]?.toUpperCase()}</span><div><b>{p.name}{p.id===room.hostId?' 👑':''}</b><small>{p.handCount} carta(s){p.ready?' • pronto':''}{p.starVote?' • ✦ sim':''}</small></div></div>)}</section>
 <section className="board"><div className="status">{room.message}</div><div className="pile"><small>ÚLTIMA CARTA</small><strong>{room.pile.at(-1)??'—'}</strong></div>
 {room.status==='lobby'&&<div className="panel"><h2>Sala criada</h2><p>Compartilhe o código <b>{room.code}</b>. Quando houver 2 a 4 jogadores, o anfitrião inicia.</p>{room.hostId===socket.id&&<button className="primary" disabled={room.players.length<2} onClick={()=>socket.emit('start',room.code)}>Iniciar partida</button>}</div>}
 {room.status==='focus'&&<div className="panel focus"><div className="pulse">◎</div><h2>Sincronizem</h2><p>Observe suas cartas. Quando estiver preparado, marque “Pronto”.</p><button className="primary" disabled={!!me?.ready} onClick={()=>socket.emit('ready',room.code)}>{me?.ready?'Aguardando...':'Estou pronto'}</button></div>}
 {room.status==='playing'&&<><div className="hand">{me?.hand.map((v,i)=><button key={v} disabled={i!==0} className="card" onClick={()=>socket.emit('play',{code:room.code,value:v})}><span>{v}</span><small>{i===0?'TOQUE PARA JOGAR':'aguarde'}</small></button>)}</div><div className="actions"><button disabled={room.stars<1} onClick={()=>socket.emit(me?.starVote?'voteStar':'proposeStar',room.code)}>✦ {me?.starVote?'Confirmar estrela':'Propor estrela'}</button></div></>}
 {(room.status==='won'||room.status==='lost')&&<div className="panel"><h2>{room.status==='won'?'Vocês conseguiram!':'Fim de jogo'}</h2><p>{room.message}</p>{room.hostId===socket.id&&<button className="primary" onClick={()=>socket.emit('start',room.code)}>Jogar novamente</button>}</div>}
 </section>{tutorial&&<Tutorial close={()=>setTutorial(false)}/>}</main>
}
createRoot(document.getElementById('root')!).render(<App/>);
